### PR TITLE
Better Handle textContent of DocumentFragment

### PR DESCRIPTION
**Pull request by mattdsteele**
Original commit via @CaptainCodeman against shadydom, PR at
https://github.com/webcomponents/shadydom/pull/147. If I was better at Git I'd have preserve the original commit, but merge conflicts prevented me from applying a patch directly.

This fixes a few issues we were seeing with ShadyDOM and AngularJS, namely https://github.com/webcomponents/webcomponentsjs/issues/777

I wasn't able to get WCT to run locally, so you might want to double check that all tests are passing and what not, but this worked for my scenarios.

Thanks again @CaptainCodeman for doing this work!

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks!

**Comment by matthewp** [comment]
I'll pull down the latest shadydom and merge.

**Comment by matthewp** [comment]
This is in 1.0.7. Thanks!

**Comment by CaptainCodeman** [comment]
I think the merge conflicts are due to other changes to the built files that are committed to the repo since that PR has been sat waiting, including the built files committed to the repo. One approach would be to rebase the branch onto the latest master - none of the conflicts are for any of the source, just the built files (which would be re-built anyway).

**Pull request merged**
